nodes = [
    "node-1",
    "node-2",
    "node-3",
    "node-4",
    "node-5",
    "node-6",
]

pods = [
    "adservice-0",
    "adservice-1",
    "adservice-2",
    "adservice2-0",
    "cartservice-0",
    "cartservice-1",
    "cartservice-2",
    "cartservice2-0",
    "checkoutservice-0",
    "checkoutservice-1",
    "checkoutservice-2",
    "checkoutservice2-0",
    "currencyservice-0",
    "currencyservice-1",
    "currencyservice-2",
    "currencyservice2-0",
    "emailservice-0",
    "emailservice-1",
    "emailservice-2",
    "emailservice2-0",
    "frontend-0",
    "frontend-1",
    "frontend-2",
    "frontend2-0",
    "paymentservice-0",
    "paymentservice-1",
    "paymentservice-2",
    "paymentservice2-0",
    "productcatalogservice-0",
    "productcatalogservice-1",
    "productcatalogservice-2",
    "productcatalogservice2-0",
    "recommendationservice-0",
    "recommendationservice-1",
    "recommendationservice-2",
    "recommendationservice2-0",
    "redis-cart-0",
    "redis-cart2-0",
    "shippingservice-0",
    "shippingservice-1",
    "shippingservice-2",
    "shippingservice2-0",
]

services = [
    "adservice-grpc",
    "adservice-http",
    "cartservice-grpc",
    "checkoutservice-grpc",
    "currencyservice-grpc",
    "emailservice-grpc",
    "frontend-http",
    "paymentservice-grpc",
    "productcatalogservice-grpc",
    "recommendationservice-grpc",
    "shippingservice-grpc",
]

__all__ = ["nodes", "pods", "services"]
