LOG_KEYWORDS = [
    "error",
    "fail",
    "failure",
    "fatal",
    "alert",
    "exception",
    "stacktrace",
    "denied",
    "unauthorized",
    "forbidden",
    "rejected",
    "timeout",
    "refused",
    "unreachable",
    "disconnect",
    "abort",
    "crash",
    "panic",
    "corrupt",
    "invalid",
    "mismatch",
    "cannot",
    "unable",
    "not found",
    "broken",
    "kill",
]

__all__ = ["LOG_KEYWORDS"]
